Revert "Use std namespace for snprintf."
This reverts commit 1c58876185d2a4ed87dac4a54b82f607e74f55fd.

snprintf() is not in the std namespace. This fixes the build error below:

src/lib_json/json_writer.cpp:33:18: error: 'snprintf' is not a member of 'std'