Doxybuild: Error message if doxygen not found
Running doxygen without existing doxygen program
led to the following error message:

Deleting directory: dist/doxygen
Running:  /home/koalo/jsoncpp/doc/doxyfile
Traceback (most recent call last):
  File "doxybuild.py", line 169, in <module>
    main()
  File "doxybuild.py", line 166, in main
    build_doc( options )
  File "doxybuild.py", line 116, in build_doc
    ok = run_doxygen( options.doxygen_path, 'doc/doxyfile', 'doc',
is_silent=options.silent )
  File "doxybuild.py", line 67, in run_doxygen
    process = subprocess.Popen( cmd )
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

This patch introduces a better error message.

Signed-off-by: Florian Meier <florian.meier@koalo.de>